// //app/layout.tsx

// import type { Metadata } from "next";
// import { Merriweather_Sans, Mulish } from "next/font/google";
// import "./globals.css";
// import { Header } from "@/components/Header";


// const mulish = Mulish({
//   variable: "--font-mulish",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// const merriweatherSans = Merriweather_Sans({
//   variable: "--font-merriweather-sans",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${mulish.className} antialiased bg-white`}
//       >
//         <Header fontClass={merriweatherSans.className} />
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Merriweather_Sans, Mulish } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const merriweatherSans = Merriweather_Sans({
  variable: "--font-merriweather-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Survei Digital Wisatawan Nusantara",
  description: "Asisten AI untuk Survei Digital Wisatawan Nusantara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body
        className={`${mulish.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Header fontClass={merriweatherSans.className} /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}